package co.com.fcv.training.citas.application;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.*;
import java.util.*;

@Service
public class SchedulingService {
    public record Specialty(Long id,String code,String name,int durationMinutes,boolean general,boolean active) {}
    public record Block(Long id,Long locationId,LocalDate date,LocalTime start,LocalTime end) {}
    public record Available(Long professionalId,String professionalName,LocalDateTime startAt,LocalDateTime endAt) {}
    public record Appointment(Long id,String status,LocalDateTime startAt,LocalDateTime endAt) {}
    private record LockedSlot(Long id,LocalDateTime startAt,LocalDateTime endAt,Long appointmentId) {}
    private final JdbcTemplate jdbc; private final Clock clock;
    public SchedulingService(JdbcTemplate jdbc, Clock clock) { this.jdbc=jdbc; this.clock=clock; }

    public List<Map<String,Object>> catalog(String name) {
        String sql = switch(name) {
            case "locations" -> "select id,code,name,address,city,department from locations where active=true order by name";
            case "appointment-statuses" -> "select id,code,name,is_terminal as terminal from appointment_statuses order by id";
            case "roles" -> "select id,code,name,description from roles order by id";
            case "regimes" -> "select id,code,name from insurance_regimes order by name";
            case "plans" -> "select p.id,p.code,p.name,p.eps_id as epsId,p.regime_id as regimeId from eps_plans p where p.active=true order by p.name";
            default -> throw new IllegalArgumentException("Catálogo no soportado");
        }; return jdbc.queryForList(sql);
    }
    public List<Specialty> specialties(boolean activeOnly) { return jdbc.query("select id,code,name,appointment_duration_minutes,is_general,active from specialties " + (activeOnly?"where active=true ":"") + "order by name", (r,n)->new Specialty(r.getLong(1),r.getString(2),r.getString(3),r.getInt(4),r.getBoolean(5),r.getBoolean(6))); }
    public List<Map<String,Object>> professionals() { return jdbc.queryForList("select p.id,p.professional_code as professionalCode,p.license_number as licenseNumber,p.active,concat(u.first_name,' ',u.last_name) as name,u.email from professionals p join users u on u.id=p.user_id order by u.first_name,u.last_name"); }
    @Transactional public Specialty createSpecialty(String code,String name,int duration,boolean general) { validateDuration(duration); Long id=insert("insert into specialties(code,name,appointment_duration_minutes,is_general,requires_admin_approval,active) values (?,?,?,?,?,true)",code,name,duration,general,!general); return specialty(id); }
    @Transactional public Specialty updateSpecialty(Long id,String name,Integer duration,Boolean active) { Specialty old=specialty(id); int d=duration==null?old.durationMinutes():duration; validateDuration(d); jdbc.update("update specialties set name=?,appointment_duration_minutes=?,active=? where id=?", name==null?old.name():name,d,active==null?old.active():active,id); return specialty(id); }
    public Long createProfessional(String first,String last,String docType,String doc,String email,String phone,String passwordHash,String code,String license) {
        Long user=insert("insert into users(first_name,last_name,document_type,document_number,email,phone,password_hash,active,email_verified) values (?,?,?,?,?,?,?,true,false)",first,last,docType,doc,email,phone,passwordHash);
        jdbc.update("insert into user_roles(user_id,role_id) select ?,id from roles where code='PROFESSIONAL'",user);
        return insert("insert into professionals(user_id,professional_code,license_number,active) values (?,?,?,true)",user,code,license);
    }
    @Transactional public void setProfessionalSpecialties(Long professionalId,List<Long> ids,Long primary) { requireProfessional(professionalId); if(ids==null||ids.isEmpty()||primary==null||!ids.contains(primary)) throw new IllegalArgumentException("Asignación primaria requerida"); for(Long id:ids) { if(count("select count(*) from specialties where id=?",id)==0) throw notFound("Especialidad"); } jdbc.update("delete from professional_specialties where professional_id=?",professionalId); for(Long id:ids) jdbc.update("insert into professional_specialties(professional_id,specialty_id,is_primary,active) values (?,?,?,true)",professionalId,id,id.equals(primary)); }
    @Transactional public void setProfessionalLocations(Long professionalId,List<Long> ids) { requireProfessional(professionalId); if(ids==null||ids.isEmpty()||ids.size()>2) throw new IllegalArgumentException("Debe asignar una o dos sedes"); for(Long id:ids) if(count("select count(*) from locations where id=? and active=true",id)==0) throw notFound("Sede"); jdbc.update("delete from professional_locations where professional_id=?",professionalId); for(Long id:ids) jdbc.update("insert into professional_locations(professional_id,location_id,active) values (?,?,true)",professionalId,id); }
    public void setProfessionalActive(Long id,boolean active) { if(jdbc.update("update professionals set active=? where id=?",active,id)==0) throw notFound("Profesional"); }
    @Transactional public Block createBlock(Long userId,Long locationId,LocalDate date,LocalTime start,LocalTime end) { Long professional=professionalForUser(userId); validateBlock(professional,locationId,date,start,end,null); Long id=insert("insert into availability_blocks(professional_id,location_id,available_date,start_time,end_time,active) values (?,?,?,?,?,true)",professional,locationId,date,start,end); createSlots(id,date,start,end); return new Block(id,locationId,date,start,end); }
    public List<Block> blocks(Long userId,LocalDate date,Long location) { Long professional=professionalForUser(userId); String sql="select id,location_id,available_date,start_time,end_time from availability_blocks where professional_id=? and active=true"; List<Object> ps=new ArrayList<>(List.of(professional)); if(date!=null){sql+=" and available_date=?";ps.add(date);}if(location!=null){sql+=" and location_id=?";ps.add(location);}sql+=" order by available_date,start_time";return jdbc.query(sql,(r,n)->new Block(r.getLong(1),r.getLong(2),r.getObject(3,LocalDate.class),r.getObject(4,LocalTime.class),r.getObject(5,LocalTime.class)),ps.toArray()); }
    @Transactional public Block updateBlock(Long userId,Long id,Long location,LocalDate date,LocalTime start,LocalTime end) { Long professional=professionalForUser(userId); Block old=jdbc.query("select id,location_id,available_date,start_time,end_time from availability_blocks where id=? and professional_id=? and active=true for update",(r,n)->new Block(r.getLong(1),r.getLong(2),r.getObject(3,LocalDate.class),r.getObject(4,LocalTime.class),r.getObject(5,LocalTime.class)),id,professional).stream().findFirst().orElseThrow(()->notFound("Bloque")); if(count("select count(*) from professional_slots where availability_block_id=? and appointment_id is not null",id)>0) throw conflict("El bloque tiene citas comprometidas"); Long lid=location==null?old.locationId():location; LocalDate d=date==null?old.date():date; LocalTime s=start==null?old.start():start,e=end==null?old.end():end; validateBlock(professional,lid,d,s,e,id); jdbc.update("update availability_blocks set location_id=?,available_date=?,start_time=?,end_time=? where id=?",lid,d,s,e,id);jdbc.update("delete from professional_slots where availability_block_id=?",id);createSlots(id,d,s,e);return new Block(id,lid,d,s,e); }
    @Transactional public void deleteBlock(Long userId,Long id) { Long professional=professionalForUser(userId); if(count("select count(*) from availability_blocks where id=? and professional_id=? and active=true",id,professional)==0) throw notFound("Bloque");if(count("select count(*) from professional_slots where availability_block_id=? and appointment_id is not null",id)>0)throw conflict("El bloque tiene citas comprometidas");jdbc.update("delete from professional_slots where availability_block_id=?",id);jdbc.update("update availability_blocks set active=false where id=?",id); }
    public List<Available> availability(Long location,Long specialty,Long professional,LocalDate date) { Specialty s=specialty(specialty); String sql="select ps.start_at,ps.end_at,p.id,u.first_name,u.last_name from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id join professionals p on p.id=b.professional_id join users u on u.id=p.user_id join professional_specialties x on x.professional_id=p.id and x.specialty_id=? and x.active=true join professional_locations l on l.professional_id=p.id and l.location_id=b.location_id and l.active=true where b.active=true and p.active=true and ps.appointment_id is null and b.location_id=? and b.available_date=?"+(professional==null?"":" and p.id=?")+" order by p.id,ps.start_at"; List<Object> args=new ArrayList<>(List.of(specialty,location,date));if(professional!=null)args.add(professional);List<Available> raw=jdbc.query(sql,(r,n)->new Available(r.getLong(3),r.getString(4)+" "+r.getString(5),r.getObject(1,LocalDateTime.class),r.getObject(2,LocalDateTime.class)),args.toArray());if(s.durationMinutes()==30)return raw;List<Available> out=new ArrayList<>();for(int i=0;i+1<raw.size();i++){Available a=raw.get(i),b=raw.get(i+1);if(a.professionalId().equals(b.professionalId())&&a.endAt().equals(b.startAt()))out.add(new Available(a.professionalId(),a.professionalName(),a.startAt(),b.endAt()));}return out; }
    @Transactional public Appointment reserve(Long user,Long professional,Long location,Long specialtyId,LocalDateTime start,String reason) { Specialty specialty=specialty(specialtyId); int minutes=specialty.durationMinutes(); LocalDateTime end=start.plusMinutes(minutes); if(start.isBefore(LocalDateTime.now(clock)))throw new IllegalArgumentException("La cita debe ser futura"); if(count("select count(*) from professionals p join professional_specialties x on x.professional_id=p.id and x.specialty_id=? and x.active=true join professional_locations l on l.professional_id=p.id and l.location_id=? and l.active=true where p.id=? and p.active=true and ?=(select 1)",specialtyId,location,professional,1)==0)throw conflict("Profesional no disponible para la selección"); List<LockedSlot> lockedSlots=jdbc.query("select ps.id,ps.start_at,ps.end_at,ps.appointment_id from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id where b.professional_id=? and b.location_id=? and b.active=true and ps.start_at>=? and ps.end_at<=? order by ps.start_at for update",(r,n)->{Object appointmentId=r.getObject(4);return new LockedSlot(r.getLong(1),r.getObject(2,LocalDateTime.class),r.getObject(3,LocalDateTime.class),appointmentId==null?null:((Number)appointmentId).longValue());},professional,location,start,end); if(lockedSlots.size()!=minutes/30)throw conflict("Franja no disponible"); for(int i=1;i<lockedSlots.size();i++)if(!lockedSlots.get(i-1).endAt().equals(lockedSlots.get(i).startAt()))throw conflict("Slots no consecutivos"); if(lockedSlots.stream().anyMatch(s->s.appointmentId()!=null))throw conflict("Franja ya reservada"); List<Long> slots=lockedSlots.stream().map(LockedSlot::id).toList(); String status=specialty.general()?"APPROVED":"REQUESTED"; Long affiliation=jdbc.query("select id from user_insurance_affiliations where user_id=? and is_current=true order by id desc limit 1",(r,n)->r.getLong(1),user).stream().findFirst().orElse(null);Long statusId=statusId(status);Long appointment=insert("insert into appointments(patient_user_id,professional_id,location_id,specialty_id,insurance_affiliation_id,status_id,reason,scheduled_start_at,scheduled_end_at,created_by_user_id,approved_at) values (?,?,?,?,?,?,?,?,?,?,?)",user,professional,location,specialtyId,affiliation,statusId,reason,start,end,user,specialty.general()?LocalDateTime.now(clock):null);int claimed=jdbc.update("update professional_slots set appointment_id=? where appointment_id is null and id in ("+String.join(",",Collections.nCopies(slots.size(),"?"))+")",concat(appointment,slots));if(claimed!=slots.size())throw conflict("Franja ya reservada");jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",appointment,statusId,specialty.general()?null:user,specialty.general()?"SYSTEM":"USER",specialty.general()?"Aprobación automática":reason);return new Appointment(appointment,status,start,end); }
    public List<Map<String,Object>> pending() { return jdbc.queryForList("select a.id,a.scheduled_start_at as startAt,a.scheduled_end_at as endAt,concat(patient.first_name,' ',patient.last_name) as patientName,concat(professional_user.first_name,' ',professional_user.last_name) as professionalName,s.name as specialtyName,l.name as locationName,s.appointment_duration_minutes as durationMinutes from appointments a join appointment_statuses st on st.id=a.status_id join users patient on patient.id=a.patient_user_id join professionals p on p.id=a.professional_id join users professional_user on professional_user.id=p.user_id join specialties s on s.id=a.specialty_id join locations l on l.id=a.location_id where st.code='REQUESTED' and s.is_general=false order by a.scheduled_start_at"); }
    @Transactional public Appointment decide(Long admin,Long appointment,String decision,String reason) { if(!Set.of("APPROVE","REJECT").contains(decision))throw new IllegalArgumentException("Decisión inválida"); if("REJECT".equals(decision)&&(reason==null||reason.isBlank()))throw new IllegalArgumentException("Motivo de rechazo obligatorio"); Map<String,Object> a=jdbc.queryForMap("select a.id,a.scheduled_start_at,a.scheduled_end_at from appointments a join appointment_statuses s on s.id=a.status_id join specialties sp on sp.id=a.specialty_id where a.id=? and s.code='REQUESTED' and sp.is_general=false for update",appointment);String status="APPROVE".equals(decision)?"APPROVED":"REJECTED";Long sid=statusId(status);jdbc.update("update appointments set status_id=?,approved_by_user_id=?,approved_at=? where id=?",sid,admin,LocalDateTime.now(clock),appointment);if("REJECTED".equals(status))jdbc.update("update professional_slots set appointment_id=null where appointment_id=?",appointment);jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",appointment,sid,admin,"ADMIN",reason);return new Appointment(appointment,status,(LocalDateTime)a.get("scheduled_start_at"),(LocalDateTime)a.get("scheduled_end_at")); }
    public List<Map<String,Object>> mine(Long user,String status,LocalDate date){String q="select a.id,st.code as status,a.scheduled_start_at as startAt,a.scheduled_end_at as endAt,s.name as specialtyName,l.name as locationName,concat(u.first_name,' ',u.last_name) as professionalName,(select h.reason from appointment_status_history h where h.appointment_id=a.id and h.reason is not null order by h.id desc limit 1) as rejectionReason from appointments a join appointment_statuses st on st.id=a.status_id join specialties s on s.id=a.specialty_id join locations l on l.id=a.location_id join professionals p on p.id=a.professional_id join users u on u.id=p.user_id where a.patient_user_id=?";List<Object> x=new ArrayList<>(List.of(user));if(status!=null){q+=" and st.code=?";x.add(status);}if(date!=null){q+=" and date(a.scheduled_start_at)=?";x.add(date);}return jdbc.queryForList(q+" order by a.scheduled_start_at desc",x.toArray());}
    @Transactional public Appointment cancel(Long user,Long id){Map<String,Object> a=jdbc.queryForMap("select a.scheduled_start_at,a.scheduled_end_at from appointments a join appointment_statuses s on s.id=a.status_id where a.id=? and a.patient_user_id=? and s.is_terminal=false for update",id,user);if(!((LocalDateTime)a.get("scheduled_start_at")).isAfter(LocalDateTime.now(clock)))throw new IllegalArgumentException("Solo se puede cancelar una cita futura");Long sid=statusId("CANCELLED");jdbc.update("update appointments set status_id=? where id=?",sid,id);jdbc.update("update professional_slots set appointment_id=null where appointment_id=?",id);jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",id,sid,user,"USER","Cancelación por usuario");return new Appointment(id,"CANCELLED",(LocalDateTime)a.get("scheduled_start_at"),(LocalDateTime)a.get("scheduled_end_at"));}
    @Transactional public Map<String,Object> requestReschedule(Long user,Long appointment,LocalDateTime start){Map<String,Object>a=jdbc.queryForMap("select a.professional_id,a.location_id,a.specialty_id,a.scheduled_start_at,a.scheduled_end_at,s.appointment_duration_minutes from appointments a join appointment_statuses st on st.id=a.status_id join specialties s on s.id=a.specialty_id where a.id=? and a.patient_user_id=? and st.code='APPROVED' for update",appointment,user);if(!((LocalDateTime)a.get("scheduled_start_at")).isAfter(LocalDateTime.now(clock)))throw new IllegalArgumentException("La cita no es elegible para reprogramación");int minutes=((Number)a.get("appointment_duration_minutes")).intValue();LocalDateTime end=start.plusMinutes(minutes);List<LockedSlot> slots=jdbc.query("select ps.id,ps.start_at,ps.end_at,ps.appointment_id from professional_slots ps join availability_blocks b on b.id=ps.availability_block_id where b.professional_id=? and b.location_id=? and b.active=true and ps.start_at>=? and ps.end_at<=? and ps.appointment_id is null and ps.reschedule_request_id is null order by ps.start_at for update",(r,n)->new LockedSlot(r.getLong(1),r.getObject(2,LocalDateTime.class),r.getObject(3,LocalDateTime.class),null),a.get("professional_id"),a.get("location_id"),start,end);if(slots.size()!=minutes/30)throw conflict("Nueva franja no disponible");for(int i=1;i<slots.size();i++)if(!slots.get(i-1).endAt().equals(slots.get(i).startAt()))throw conflict("Slots no consecutivos");Long pending=jdbc.queryForObject("select id from reschedule_statuses where code='PENDING'",Long.class);if(count("select count(*) from reschedule_requests where appointment_id=? and status_id=?",appointment,pending)>0)throw conflict("Ya existe una reprogramación pendiente");Long id=insert("insert into reschedule_requests(appointment_id,requested_by_user_id,status_id,requested_start_at,requested_end_at) values (?,?,?,?,?)",appointment,user,pending,start,end);for(LockedSlot slot:slots)jdbc.update("update professional_slots set reschedule_request_id=? where id=? and appointment_id is null and reschedule_request_id is null",id,slot.id());return Map.of("id",id,"status","PENDING","startAt",start,"endAt",end);}
    @Transactional public Map<String,Object> decideReschedule(Long admin,Long request,String decision,String reason){if(!Set.of("APPROVE","REJECT").contains(decision))throw new IllegalArgumentException("Decisión inválida");if("REJECT".equals(decision)&&(reason==null||reason.isBlank()))throw new IllegalArgumentException("Motivo de rechazo obligatorio");Map<String,Object>r=jdbc.queryForMap("select rr.appointment_id,rr.requested_start_at,rr.requested_end_at from reschedule_requests rr join reschedule_statuses s on s.id=rr.status_id where rr.id=? and s.code='PENDING' for update",request);Long appointment=((Number)r.get("appointment_id")).longValue();String result="APPROVE".equals(decision)?"APPROVED":"REJECTED";Long sid=jdbc.queryForObject("select id from reschedule_statuses where code=?",Long.class,result);if("APPROVE".equals(decision)){jdbc.update("update professional_slots set appointment_id=null where appointment_id=?",appointment);jdbc.update("update professional_slots set appointment_id=?,reschedule_request_id=null where reschedule_request_id=?",appointment,request);jdbc.update("update appointments set scheduled_start_at=?,scheduled_end_at=? where id=?",r.get("requested_start_at"),r.get("requested_end_at"),appointment);jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",appointment,statusId("APPROVED"),admin,"ADMIN","Reprogramación aprobada");}else jdbc.update("update professional_slots set reschedule_request_id=null where reschedule_request_id=?",request);jdbc.update("update reschedule_requests set status_id=?,decision_reason=?,decided_by_user_id=?,decided_at=? where id=?",sid,reason,admin,LocalDateTime.now(clock),request);return Map.of("id",request,"status",result,"appointmentId",appointment);}
    public List<Map<String,Object>> pendingReschedules(){return jdbc.queryForList("select rr.id,rr.appointment_id as appointmentId,rr.requested_start_at as startAt,rr.requested_end_at as endAt,concat(u.first_name,' ',u.last_name) as patientName from reschedule_requests rr join reschedule_statuses s on s.id=rr.status_id join appointments a on a.id=rr.appointment_id join users u on u.id=a.patient_user_id where s.code='PENDING' order by rr.created_at");}
    public List<Map<String,Object>> agenda(Long user,LocalDate from,LocalDate to,Long location){Long p=professionalForUser(user);String q="select a.id,a.scheduled_start_at as startAt,a.scheduled_end_at as endAt,l.name as locationName,s.name as specialtyName,concat(u.first_name,' ',u.last_name) as patientName from appointments a join appointment_statuses st on st.id=a.status_id join locations l on l.id=a.location_id join specialties s on s.id=a.specialty_id join users u on u.id=a.patient_user_id where a.professional_id=? and st.code='APPROVED'";List<Object>x=new ArrayList<>(List.of(p));if(from!=null){q+=" and date(a.scheduled_start_at)>=?";x.add(from);}if(to!=null){q+=" and date(a.scheduled_start_at)<=?";x.add(to);}if(location!=null){q+=" and a.location_id=?";x.add(location);}return jdbc.queryForList(q+" order by a.scheduled_start_at",x.toArray());}
    @Transactional public Appointment close(Long user,Long id,String status){if(!Set.of("COMPLETED","NO_SHOW").contains(status))throw new IllegalArgumentException("Estado de cierre inválido");Long p=professionalForUser(user);Map<String,Object>a=jdbc.queryForMap("select a.scheduled_start_at,a.scheduled_end_at from appointments a join appointment_statuses s on s.id=a.status_id where a.id=? and a.professional_id=? and s.code='APPROVED' for update",id,p);if(((LocalDateTime)a.get("scheduled_end_at")).isAfter(LocalDateTime.now(clock)))throw new IllegalArgumentException("La cita todavía no es aplicable para cierre");Long sid=statusId(status);jdbc.update("update appointments set status_id=? where id=?",sid,id);jdbc.update("insert into appointment_status_history(appointment_id,status_id,changed_by_user_id,change_source,reason) values (?,?,?,?,?)",id,sid,user,"PROFESSIONAL",null);return new Appointment(id,status,(LocalDateTime)a.get("scheduled_start_at"),(LocalDateTime)a.get("scheduled_end_at"));}
    public List<Map<String,Object>> history(Long user,Long id,boolean admin){String q="select h.id,st.code as status,h.changed_at as changedAt,h.change_source as source,h.reason,concat(u.first_name,' ',u.last_name) as actorName from appointment_status_history h join appointment_statuses st on st.id=h.status_id left join users u on u.id=h.changed_by_user_id join appointments a on a.id=h.appointment_id where h.appointment_id=? and (a.patient_user_id=? or a.professional_id=(select id from professionals where user_id=?)"+(admin?" or 1=1":"")+")";return jdbc.queryForList(q+" order by h.changed_at",id,user,user);}
    private void validateBlock(Long professional,Long location,LocalDate date,LocalTime start,LocalTime end,Long except) { if(!date.isAfter(LocalDate.now(clock))||!end.isAfter(start)||start.getMinute()%30!=0||end.getMinute()%30!=0)throw new IllegalArgumentException("Bloque futuro y alineado a 30 minutos requerido");if(count("select count(*) from professionals p join professional_locations l on l.professional_id=p.id and l.location_id=? and l.active=true where p.id=? and p.active=true",location,professional)==0)throw conflict("Profesional no habilitado en sede");String q="select count(*) from availability_blocks where professional_id=? and active=true and available_date=? and start_time < ? and end_time > ?"+(except==null?"":" and id<>?");List<Object> x=new ArrayList<>(List.of(professional,date,end,start));if(except!=null)x.add(except);if(count(q,x.toArray())>0)throw conflict("Bloque solapado"); }
    private void createSlots(Long block,LocalDate date,LocalTime start,LocalTime end){for(LocalTime t=start;t.isBefore(end);t=t.plusMinutes(30))jdbc.update("insert into professional_slots(availability_block_id,start_at,end_at) values (?,?,?)",block,LocalDateTime.of(date,t),LocalDateTime.of(date,t.plusMinutes(30)));}
    private Long professionalForUser(Long user){return jdbc.query("select id from professionals where user_id=? and active=true",(r,n)->r.getLong(1),user).stream().findFirst().orElseThrow(()->notFound("Profesional"));}
    private void requireProfessional(Long id){if(count("select count(*) from professionals where id=?",id)==0)throw notFound("Profesional");}
    private Specialty specialty(Long id){return jdbc.query("select id,code,name,appointment_duration_minutes,is_general,active from specialties where id=?",(r,n)->new Specialty(r.getLong(1),r.getString(2),r.getString(3),r.getInt(4),r.getBoolean(5),r.getBoolean(6)),id).stream().findFirst().filter(Specialty::active).orElseThrow(()->notFound("Especialidad activa"));}
    private Long statusId(String code){return jdbc.query("select id from appointment_statuses where code=?",(r,n)->r.getLong(1),code).stream().findFirst().orElseThrow(()->new IllegalStateException("Estado faltante"));}
    private Long insert(String sql,Object... args){KeyHolder keys=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},keys);return Objects.requireNonNull(keys.getKey()).longValue();}
    private int count(String sql,Object... args){Integer i=jdbc.queryForObject(sql,Integer.class,args);return i==null?0:i;}
    private void validateDuration(int d){if(d!=30&&d!=60)throw new IllegalArgumentException("Duración debe ser 30 o 60 minutos");}
    private SchedulingFailure notFound(String s){return new SchedulingFailure(SchedulingFailure.Kind.NOT_FOUND,s+" no encontrado");} private SchedulingFailure conflict(String s){return new SchedulingFailure(SchedulingFailure.Kind.CONFLICT,s);} private Object[] concat(Object first,List<Long> rest){Object[] r=new Object[rest.size()+1];r[0]=first;for(int i=0;i<rest.size();i++)r[i+1]=rest.get(i);return r;}
}
